repos:
  - repo: https://github.com/google/yapf
    rev: v0.32.0  # Keep the same as requirements-dev.txt
    hooks:
    -   id: yapf
        args: ['-i', '--recursive', '--parallel', '--exclude build/**']
        additional_dependencies: [toml]
  - repo: https://github.com/pylint-dev/pylint
    rev: v2.8.2  # Keep the same as requirements-dev.txt
    hooks:
      - id: pylint