repos:
  - repo: local
    hooks:
      - id: format_lint
        name: vLLM format and lint script
        language: system
        always_run: true
        pass_filenames: false
        entry: ./format.sh