[build-system]
requires = [
    "ninja",
    "packaging",
    "setuptools",
    "torch >= 2.0.1", # downgrade to accommodate ROCm supported version
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    # "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    # "I",
]
ignore = [
    # star imports
    "F405", "F403",
    # lambda expression assignment
    "E731",
    # line too long, handled by black formatting
    "E501",
]
