name: AMD ROCm Build

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rocm:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Check environment
      run: |
        docker --version
    - name: Build Docker
      run: |
        docker build -t rocm -f Dockerfile.rocm .
    - name: Run Sanity Test
      run: |
        # detele any existing container
        docker rm -f $(docker ps -a -q)
        # run the container
        docker run -d --p 8000:8000 rocm
        # wait for the server to start
        while [ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8000)" != "200" ]; do sleep 1; done
        # run the sanity test
        python examples/openai_completion_client.py
        # remove the container
        docker rm -f $(docker ps -a -q)


